# Contenu de ce fichier chargé automatiquement et accessible
# dans les templates via `site.*. Par exemple {{ site.title }}

title: Mozilla francophone
subtitle: La communauté Mozilla francophone
description: Bienvenue sur le site de la communauté Mozilla francophone, aidez-nous et rejoignez-nous pour promouvoir un internet libre et ouvert à tous !
